server:
  port: 8769

#配置从类路径下的config文件夹下读取配置文件 
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:configs        
  profiles:
    active:
    - native
#配置eureka服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: config-server.com
    prefer-ip-address: true       
#开启端点监控
management:
  security:
    enabled: false